"""empty message

Revision ID: 23a8a1221c4c
Revises: 9deb8330a39a
Create Date: 2026-01-08 22:14:29.234673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a8a1221c4c'
down_revision = '9deb8330a39a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_demands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('time_period', sa.Integer(), nullable=False),
    sa.Column('demand', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_fulfillment_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('demand > 0', name='ck_demand_positive'),
    sa.CheckConstraint('min_fulfillment_pct <= 100', name='ck_min_fulfillment_max'),
    sa.CheckConstraint('min_fulfillment_pct >= 0', name='ck_min_fulfillment_nonnegative'),
    sa.CheckConstraint('time_period >= 1', name='ck_demand_period_positive'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'plant_id', 'time_period', name='uq_demand_per_plant_period')
    )
    with op.batch_alter_table('plant_demands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plant_demands_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_demands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plant_demands_organization_id'))

    op.drop_table('plant_demands')
    # ### end Alembic commands ###
