"""empty message

Revision ID: 9deb8330a39a
Revises: 20251228_add_plant_production_cost
Create Date: 2025-12-28 18:28:39.573649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9deb8330a39a'
down_revision = '20251228_add_plant_production_cost'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        # Add with server default so SQLite can create the NOT NULL column without failing.
        batch_op.add_column(
            sa.Column(
                'holding_cost',
                sa.Numeric(precision=12, scale=2),
                nullable=False,
                server_default=sa.text("0"),
            )
        )

    with op.batch_alter_table('transport_routes', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'cost_per_ton',
                sa.Numeric(precision=12, scale=2),
                nullable=False,
                server_default=sa.text("0"),
            )
        )
        batch_op.add_column(sa.Column('lead_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport_routes', schema=None) as batch_op:
        batch_op.drop_column('lead_time')
        batch_op.drop_column('cost_per_ton')

    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_column('holding_cost')

    # ### end Alembic commands ###
