"""empty message

Revision ID: ab3ac8b80ee3
Revises: 23a8a1221c4c
Create Date: 2026-01-08 22:37:59.576670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3ac8b80ee3'
down_revision = '23a8a1221c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinker_capacities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planning_scenario_id', sa.Integer(), nullable=True),
    sa.Column('plant_code', sa.String(length=16), nullable=False),
    sa.Column('time_period', sa.Integer(), nullable=False),
    sa.Column('capacity_tons', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('capacity_tons >= 0', name='ck_capacity_nonnegative'),
    sa.CheckConstraint('time_period <= 3', name='ck_capacity_period_max'),
    sa.CheckConstraint('time_period >= 1', name='ck_capacity_period_min'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planning_scenario_id'], ['planning_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'planning_scenario_id', 'plant_code', 'time_period', name='uq_capacity_per_org_scenario_period')
    )
    with op.batch_alter_table('clinker_capacities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinker_capacities_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinker_capacities_planning_scenario_id'), ['planning_scenario_id'], unique=False)

    op.create_table('clinker_demands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planning_scenario_id', sa.Integer(), nullable=True),
    sa.Column('plant_code', sa.String(length=16), nullable=False),
    sa.Column('time_period', sa.Integer(), nullable=False),
    sa.Column('demand_tons', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_fulfillment_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('demand_tons > 0', name='ck_clinker_demand_positive'),
    sa.CheckConstraint('min_fulfillment_pct <= 100', name='ck_clinker_min_fulfillment_max'),
    sa.CheckConstraint('min_fulfillment_pct >= 0', name='ck_clinker_min_fulfillment_nonnegative'),
    sa.CheckConstraint('time_period <= 3', name='ck_clinker_demand_period_max'),
    sa.CheckConstraint('time_period >= 1', name='ck_clinker_demand_period_min'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planning_scenario_id'], ['planning_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'planning_scenario_id', 'plant_code', 'time_period', name='uq_demand_per_org_scenario_period')
    )
    with op.batch_alter_table('clinker_demands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinker_demands_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinker_demands_planning_scenario_id'), ['planning_scenario_id'], unique=False)

    op.create_table('hub_opening_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planning_scenario_id', sa.Integer(), nullable=True),
    sa.Column('from_code', sa.String(length=16), nullable=False),
    sa.Column('to_code', sa.String(length=16), nullable=False),
    sa.Column('opening_stock', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('opening_stock >= 0', name='ck_hub_opening_nonnegative'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planning_scenario_id'], ['planning_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'planning_scenario_id', 'from_code', 'to_code', name='uq_hub_opening_per_org_scenario')
    )
    with op.batch_alter_table('hub_opening_stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hub_opening_stocks_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hub_opening_stocks_planning_scenario_id'), ['planning_scenario_id'], unique=False)

    op.create_table('iugu_closing_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planning_scenario_id', sa.Integer(), nullable=True),
    sa.Column('plant_code', sa.String(length=16), nullable=False),
    sa.Column('time_period', sa.Integer(), nullable=False),
    sa.Column('min_close_stock', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_close_stock', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('(max_close_stock IS NULL) OR (max_close_stock >= 0)', name='ck_max_close_stock_nonnegative'),
    sa.CheckConstraint('min_close_stock >= 0', name='ck_min_close_stock_nonnegative'),
    sa.CheckConstraint('time_period <= 3', name='ck_closing_stock_period_max'),
    sa.CheckConstraint('time_period >= 1', name='ck_closing_stock_period_min'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planning_scenario_id'], ['planning_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'planning_scenario_id', 'plant_code', 'time_period', name='uq_closing_stock_per_org_scenario_period')
    )
    with op.batch_alter_table('iugu_closing_stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_iugu_closing_stocks_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_iugu_closing_stocks_planning_scenario_id'), ['planning_scenario_id'], unique=False)

    op.create_table('iugu_constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planning_scenario_id', sa.Integer(), nullable=True),
    sa.Column('from_code', sa.String(length=16), nullable=False),
    sa.Column('transport_code', sa.String(length=10), nullable=True),
    sa.Column('to_code', sa.String(length=16), nullable=True),
    sa.Column('time_period', sa.Integer(), nullable=False),
    sa.Column('constraint_type', sa.String(length=3), nullable=False),
    sa.Column('value_type', sa.String(length=3), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("constraint_type IN ('L', 'G', 'E')", name='ck_iugu_constraint_type'),
    sa.CheckConstraint("value_type IN ('C')", name='ck_iugu_constraint_value_type'),
    sa.CheckConstraint('time_period <= 3', name='ck_iugu_constraint_period_max'),
    sa.CheckConstraint('time_period >= 1', name='ck_iugu_constraint_period_min'),
    sa.CheckConstraint('value >= 0', name='ck_iugu_constraint_value_nonnegative'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planning_scenario_id'], ['planning_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'planning_scenario_id', 'from_code', 'transport_code', 'to_code', 'time_period', 'constraint_type', name='uq_iugu_constraint_unique')
    )
    with op.batch_alter_table('iugu_constraints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_iugu_constraints_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_iugu_constraints_planning_scenario_id'), ['planning_scenario_id'], unique=False)

    op.create_table('iugu_opening_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planning_scenario_id', sa.Integer(), nullable=True),
    sa.Column('plant_code', sa.String(length=16), nullable=False),
    sa.Column('opening_stock', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('opening_stock >= 0', name='ck_opening_stock_nonnegative'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planning_scenario_id'], ['planning_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'planning_scenario_id', 'plant_code', name='uq_opening_stock_per_org_scenario')
    )
    with op.batch_alter_table('iugu_opening_stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_iugu_opening_stocks_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_iugu_opening_stocks_planning_scenario_id'), ['planning_scenario_id'], unique=False)

    op.create_table('iugu_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planning_scenario_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('plant_type', sa.String(length=5), nullable=False),
    sa.Column('sources_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("plant_type IN ('IU', 'GU')", name='ck_iugu_type'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planning_scenario_id'], ['planning_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', 'planning_scenario_id', name='uq_iugu_code_per_org_scenario')
    )
    with op.batch_alter_table('iugu_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_iugu_types_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_iugu_types_planning_scenario_id'), ['planning_scenario_id'], unique=False)

    op.create_table('logistics_iugu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planning_scenario_id', sa.Integer(), nullable=True),
    sa.Column('from_code', sa.String(length=16), nullable=False),
    sa.Column('to_code', sa.String(length=16), nullable=False),
    sa.Column('transport_code', sa.String(length=10), nullable=False),
    sa.Column('time_period', sa.Integer(), nullable=False),
    sa.Column('freight_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('handling_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity_multiplier', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('freight_cost >= 0', name='ck_logistics_freight_nonnegative'),
    sa.CheckConstraint('handling_cost >= 0', name='ck_logistics_handling_nonnegative'),
    sa.CheckConstraint('quantity_multiplier > 0', name='ck_logistics_multiplier_positive'),
    sa.CheckConstraint('time_period <= 3', name='ck_logistics_period_max'),
    sa.CheckConstraint('time_period >= 1', name='ck_logistics_period_min'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planning_scenario_id'], ['planning_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'planning_scenario_id', 'from_code', 'to_code', 'transport_code', 'time_period', name='uq_logistics_route_per_period')
    )
    with op.batch_alter_table('logistics_iugu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logistics_iugu_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_logistics_iugu_planning_scenario_id'), ['planning_scenario_id'], unique=False)

    op.create_table('production_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planning_scenario_id', sa.Integer(), nullable=True),
    sa.Column('plant_code', sa.String(length=16), nullable=False),
    sa.Column('time_period', sa.Integer(), nullable=False),
    sa.Column('cost_per_ton', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('cost_per_ton > 0', name='ck_prod_cost_positive'),
    sa.CheckConstraint('time_period <= 3', name='ck_prod_cost_period_max'),
    sa.CheckConstraint('time_period >= 1', name='ck_prod_cost_period_min'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planning_scenario_id'], ['planning_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'planning_scenario_id', 'plant_code', 'time_period', name='uq_prod_cost_per_org_scenario_period')
    )
    with op.batch_alter_table('production_costs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_costs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_costs_planning_scenario_id'), ['planning_scenario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_costs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_costs_planning_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_production_costs_organization_id'))

    op.drop_table('production_costs')
    with op.batch_alter_table('logistics_iugu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logistics_iugu_planning_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_logistics_iugu_organization_id'))

    op.drop_table('logistics_iugu')
    with op.batch_alter_table('iugu_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iugu_types_planning_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_iugu_types_organization_id'))

    op.drop_table('iugu_types')
    with op.batch_alter_table('iugu_opening_stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iugu_opening_stocks_planning_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_iugu_opening_stocks_organization_id'))

    op.drop_table('iugu_opening_stocks')
    with op.batch_alter_table('iugu_constraints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iugu_constraints_planning_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_iugu_constraints_organization_id'))

    op.drop_table('iugu_constraints')
    with op.batch_alter_table('iugu_closing_stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iugu_closing_stocks_planning_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_iugu_closing_stocks_organization_id'))

    op.drop_table('iugu_closing_stocks')
    with op.batch_alter_table('hub_opening_stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hub_opening_stocks_planning_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_hub_opening_stocks_organization_id'))

    op.drop_table('hub_opening_stocks')
    with op.batch_alter_table('clinker_demands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinker_demands_planning_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_clinker_demands_organization_id'))

    op.drop_table('clinker_demands')
    with op.batch_alter_table('clinker_capacities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinker_capacities_planning_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_clinker_capacities_organization_id'))

    op.drop_table('clinker_capacities')
    # ### end Alembic commands ###
